.

diff --git a/user/cantari/env_m2 b/user/cantari/env_m2
--- a/user/cantari/env_m2
+++ b/user/cantari/env_m2
@@ -17,6 +17,11 @@ if [[ "$LFS_ENV" != "m1_root" ]];then
   exit 1
 fi
 
+if [[ ! -d /mnt/m2_filesystem/mnt/Lustucru/user ]]; then
+  echo $(basename "$0") "repo not found on mount, have you run book_m1_to_m2?"
+  exit 1
+fi
+
 echo "chroot to"  "$LFS_M2_FILESYSTEM"
 chroot "$LFS_M2_FILESYSTEM" /usr/bin/env --ignore-environment \
   HOSTNAME="$HOSTNAME"\
