environment scripts working

diff --git a/user/executable/checkpoint b/user/executable/checkpoint
--- a/user/executable/checkpoint
+++ b/user/executable/checkpoint
@@ -15,24 +15,24 @@
 set -x
 
 if [[ -z "$LFS_BUILD_DIR" ]];then
-  echo $0 "requires variable \$LFS_BUILD_DIR to be set"
+  echo $(basename "$0") "requires variable \$LFS_BUILD_DIR to be set"
   exit 1
 fi
 
 checkpoint="$1"
 if [[ -z "$checkpoint" ]];then
-  echo $0 "warning has no checkpoint name parameter - making generic 'checkpoint'"
+  echo $(basename "$0") "warning has no checkpoint name parameter - making generic 'checkpoint'"
   checkpoint="checkpoint"
 fi
 
 checkpoint_dir="$LFS_BUILD_DIR/checkpoint"
 if [[ -d "$checkpoint_dir" ]];then
-  mkdir -p "$checkpoint_dir"  || { echo $0 "failed to make checkpoint_dir" || exit 1 ; }
+  mkdir -p "$checkpoint_dir"  || { echo $(basename "$0") "failed to make checkpoint_dir" || exit 1 ; }
 fi
 
 checkpoint_file=$(mktemp --tmpdir="$checkpoint_dir" "$checkpoint.XXXXX.tgz")
 
-echo $0 "$checkpoint_file" "$LFS_M2_FILESYSTEM" 
+echo $(basename "$0") "$checkpoint_file" "$LFS_M2_FILESYSTEM" 
 tar -czf $checkpoint_file "$LFS_M2_FILESYSTEM"
 
 set +x
diff --git a/user/executable/frame b/user/executable/frame
--- a/user/executable/frame
+++ b/user/executable/frame
@@ -4,18 +4,18 @@
 script=$@
 
 if [[ -z "$LFS_BUILD_DIR" ]];then
-  echo "$0 no \$LFS_BILD_DIR"
+  echo "$(basename "$0") no \$LFS_BILD_DIR"
   exit 1
 fi
 if [[ ! -d "$LFS_BUILD_DIR/log" ]];then
-  mkdir -p "$LFS_BUILD_DIR/log" || { echo $0 "can't make log dir" && exit 2 ; }
+  mkdir -p "$LFS_BUILD_DIR/log" || { echo $(basename $(basename "$0")) "can't make log dir" && exit 2 ; }
 fi
 if [[ -z "$LFS_FRAME_LOG" ]];then
-  echo "$0 no \$LFS_FRAME_LOG"
+  echo "$(basename "$0") no \$LFS_FRAME_LOG"
   exit 3
 fi
 if [[ -z "$LFS_BUILD_LOG" ]];then
-  echo "$0 no \$LFS_BUILD_LOG"
+  echo "$(basename "$0") no \$LFS_BUILD_LOG"
   exit 4
 fi
 
