gathers mulitple build per build into a single directory

diff --git a/user/executable/checkpoint b/user/executable/checkpoint
--- a/user/executable/checkpoint
+++ b/user/executable/checkpoint
@@ -15,19 +15,19 @@
 set -x
 
 if [[ -z "$LFS_BUILD_DIR" ]];then
-  echo $(basename "$0") "requires variable \$LFS_BUILD_DIR to be set"
+  echo $(basename "$0") "requires variable \$LFS_BUILD_DIR to be set" > /dev/stderr
   exit 1
 fi
 
 checkpoint="$1"
 if [[ -z "$checkpoint" ]];then
-  echo $(basename "$0") "warning has no checkpoint name parameter - making generic 'checkpoint'"
+  echo $(basename "$0") "warning has no checkpoint name parameter - making generic 'checkpoint'" > /dev/stderr
   checkpoint="checkpoint"
 fi
 
 checkpoint_dir="$LFS_BUILD_DIR/checkpoint"
 if [[ -d "$checkpoint_dir" ]];then
-  mkdir -p "$checkpoint_dir"  || { echo $(basename "$0") "failed to make checkpoint_dir" || exit 1 ; }
+  mkdir -p "$checkpoint_dir"  || { echo $(basename "$0") "failed to make checkpoint_dir" >/dev/stderr || exit 1 ; }
 fi
 
 checkpoint_file=$(mktemp --tmpdir="$checkpoint_dir" "$checkpoint.XXXXX.tgz")
