working out interplay between the environment scripts and sudo

diff --git a/executable/LFS/book_m2_environment b/executable/LFS/book_m2_environment
--- a/executable/LFS/book_m2_environment
+++ b/executable/LFS/book_m2_environment
@@ -1,6 +1,7 @@
 #!/bin/bash
+# bash without -i resets PS1
 # Make the top of the m2 tree the root of the file system, then run the script
-set -x
+#set -x
 
 script=$@
 if [[ -z "$script" ]];then
@@ -8,16 +9,24 @@ if [[ -z "$script" ]];then
   exit
 fi
 
-if [[ -d "$PROJECT_HOME/executable/LFS" ]]; then
-  export_scripts
+if [[ -z "$M2_ROOT" ]];then
+  echo $0 "requires variable M2_ROOT to be set"
+  exit
 fi
 
-wrapped=$(mktemp)
-if [ $? -ne 0 ]; then
-    echo "$0: couldn't create temp"
-    exit 2
+if [[ -z "$TERM" ]];then
+  echo $0 "requires variable TERM to be set"
+  exit
 fi
+
+wrapped=$(mktemp --tmpdir="$M2_ROOT/tmp")
+if [ $? -ne 0 ]; then
+  echo "$0: couldn't create temp"
+  exit 2
+fi
+wrapped_basename=$(basename "$wrapped")
 chmod u+x "$wrapped"
+
 
 # Variables with the $ expand now.  Those with \$ remain as part of the document.
 cat >"$wrapped" <<-EOF
@@ -35,10 +44,10 @@ cat >"$wrapped" <<-EOF
 	LC_ALL=POSIX
 	PATH=/usr/sbin/LFS:"\$PATH"
 	MAKEFLAGS='-j12'  # this might cause problems for some builds
-	export M2_ROOT LC_ALL PATH MAKEFLAGS 
+	export LFS_ENVIRONMENT M2_ROOT LC_ALL PATH MAKEFLAGS 
 
         # repo environment
-	PROJECT="lfs-m2"
+	PROJECT="LFS-book-m2"
 	export PROJECT
 
 	# for our build scripts
@@ -47,15 +56,18 @@ cat >"$wrapped" <<-EOF
 	export BUILD_LOG FRAME_LOG        
 
 	# prompt so that dirtrack works in emacs, timezone
-	PS1=$PS1
-	PS2=$PS2
+        PS1='\n\$(/usr/sbin/LFS/Z)[\$PROJECT]\n\u@\h§\$PWD§\n> '
+        PS2='>> '
 	TZ=UTC
 	TIME_STYLE=long-iso
-        export PS1 PS2 TZ TIME_STYLE
+        export PPS1 PPS2 PS1 PS2 TZ TIME_STYLE
+
+        # a little funny, might be that we should have a build directory under root or some such
+	cd /sbin/LFS
 
 	$script
 EOF
 
-sudo chroot "$M2_ROOT" /usr/bin/env -i "$wrapped"
+chroot "$M2_ROOT" /usr/bin/env -i "/tmp/$wrapped_basename"
 
-set +x
+#set +x
