chapter 8 build scripts added now being tested

diff --git a/LFS11/executable/frame b/LFS11/executable/frame
--- a/LFS11/executable/frame
+++ b/LFS11/executable/frame
@@ -3,21 +3,24 @@
 #
 script=$@
 
-if [[ -z "$LFS_LOG_DIR" ]];then
-  echo "$0 no \$LFS_LOG_DIR"
+if [[ -z "$LFS_BUILD_DIR" ]];then
+  echo "$0 no \$LFS_BILD_DIR"
   exit 1
+fi
+if [[ ! -d "$LFS_BUILD_DIR/log" ]];then
+  mkdir -p "$LFS_BUILD_DIR/log" || { echo $0 "can't make log dir" && exit 2 ; }
 fi
 if [[ -z "$FRAME_LOG" ]];then
   echo "$0 no \$FRAME_LOG"
-  exit 2
+  exit 3
 fi
 if [[ -z "$BUILD_LOG" ]];then
   echo "$0 no \$BUILD_LOG"
   exit 4
 fi
 
-frame_log_path="$LFS_LOG_DIR/$FRAME_LOG"
-build_log_path="$LFS_LOG_DIR/$BUILD_LOG"
+frame_log_path="$LFS_BUILD_DIR/log/$FRAME_LOG"
+build_log_path="$LFS_BUILD_DIR/log/$BUILD_LOG"
 stamp=$(Z)
 cat <<EOF | tee -a "$frame_log_path" >> "$build_log_path"
 
@@ -27,10 +30,6 @@ cat <<EOF | tee -a "$frame_log_path" >> "$build_log_path"
 #
 #
 EOF
-
-#m2 does not have 'time'
-# { /usr/bin/time -a -o "$frame_log_path" $script 2>&1 >&3 3>&- | tee -a "$frame_log_path" 3>&-; } >> "$build_log_path" 3>&1
-#{ $script 2>&1 >&3 3>&- | tee -a "$frame_log_path" ; } >> "$build_log_path" 3>&1
 
 { { time $script ; } 2>&1 1>&3 | tee -a "$frame_log_path" ; } 1>> "$build_log_path" 3>&1
 
